// @index('./**/*.ts', f => `export * from '${f.path}'`)
export * from './breadcrumb/breadcrumb.component'
export * from './delete/delete.component'
export * from './error-message-list/error-message-list.component'
export * from './header/header.component'
export * from './home/home.component'
export * from './menu/left-menu/menu.component'
export * from './menu/right-menu/right-menu.component'
export * from './paginator/paginator.component'
export * from './paginator2/paginator.component'
export * from './stats/general-stats.model'
export * from './stats/general-stats/general-stats.component'
export * from './stats/online-stats.model'
export * from './stats/online-stats/online-stats.component'
export * from './stats/stats.service'
