// @index('./**/*.ts', f => `export * from '${f.path}'`)
export * from './account.service'
export * from './breadcrumb.service'
export * from './forum.service'
export * from './name.service'
export * from './post.service'
export * from './search.service'
export * from './section.service'
export * from './topic.service'
export * from './upload.service'
